# Bu tanım dosyasında bookinfo uygulaması için tanımlanan virtual service bilgileri bulunur. 
# Eşleşen uri ile host eşleştirilir. 
# Belirtilen uri değerlerine gelen istekler productpage servisine yönlendirilir.
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "bookinfo.app"
  gateways:
    - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage # Kesin olarak belirtilen uri değerinin bookinfo.app/productpage olması gerekiyor.
    - uri:
        prefix: /static # Belirtilen uri değerinin ön ekinin static olması gerekiyor. bookinfo.app/static/------ gibi.
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080