apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: my-scheduler
    plugins:
      score:
        disabled:
        - name: TaintToleration
        enabled:
        - name: MyCustomPluginA
        - name: MyCustomPluginB
  
  - schedulerName: my-scheduler-2
    plugins:
      preScore:
        disabled:
        - name: '*'
        enabled:
      score:
        disabled:
         - name: '*'