apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
	name: high-priority
value: 10000
globalDefault: false
description: "This priority class should be used for xyz service pods only."

# Oluşturduğumuz bu PriorityClass'ı pod yaml dosyasında spec.priorityClassName değerine verebiliriz.