apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example
spec:
  selector:
    matchLabels:
      app: example
  template:
     metadata:
        labels:
          app: example
     spec:
       containers:
         - name: example
           image: example